---
name: Simple CI
on:
  - push
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run test.py
        run: python test.py
      - name: Run dev.py
        run: python dev.py
      - name: Run prod.py
        run: python prod.py
